-- RUN THIS IN SUPABASE SQL EDITOR

-- 1. Create table with CORRECT types
-- If the table was partially created with errors, it's safest to drop it first if it exists but is broken.
-- However, DROP might lose data if it existed. 
-- Since the user said "relation does not exist", we are creating it fresh.

CREATE TABLE IF NOT EXISTS recently_played (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    track_id BIGINT REFERENCES songs(id), -- Songs use BIGINT
    episode_id UUID REFERENCES episodes(id), -- Episodes use UUID
    type TEXT CHECK (type IN ('music', 'podcast')),
    last_position NUMERIC DEFAULT 0, -- Seconds
    played_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT unique_user_track UNIQUE (user_id, track_id),
    CONSTRAINT unique_user_episode UNIQUE (user_id, episode_id)
);

-- 2. Enable RLS
ALTER TABLE songs ENABLE ROW LEVEL SECURITY;
ALTER TABLE podcasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE episodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE recently_played ENABLE ROW LEVEL SECURITY;

-- 3. POLICIES FOR CONTENT
-- Allow public read access
DROP POLICY IF EXISTS "Public Read Songs" ON songs;
CREATE POLICY "Public Read Songs" ON songs FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Podcasts" ON podcasts;
CREATE POLICY "Public Read Podcasts" ON podcasts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Episodes" ON episodes;
CREATE POLICY "Public Read Episodes" ON episodes FOR SELECT USING (true);

-- Allow Authenticated Users (Admins) to Insert
DROP POLICY IF EXISTS "Admin Insert Songs" ON songs;
CREATE POLICY "Admin Insert Songs" ON songs FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Admin Insert Podcasts" ON podcasts;
CREATE POLICY "Admin Insert Podcasts" ON podcasts FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Admin Insert Episodes" ON episodes;
CREATE POLICY "Admin Insert Episodes" ON episodes FOR INSERT TO authenticated WITH CHECK (true);

-- 4. POLICIES FOR RECENTLY PLAYED
DROP POLICY IF EXISTS "User History Insert" ON recently_played;
CREATE POLICY "User History Insert" ON recently_played FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "User History Select" ON recently_played;
CREATE POLICY "User History Select" ON recently_played FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "User History Update" ON recently_played;
CREATE POLICY "User History Update" ON recently_played FOR UPDATE TO authenticated USING (auth.uid() = user_id);
