-- ==============================================================================
-- StreamLite Database Schema (Supabase / PostgreSQL)
-- ==============================================================================

-- Enable UUID extension for unique identifiers
create extension if not exists "uuid-ossp";

-- ==========================================
-- 1. PUBLIC PROFILES (User Metadata)
-- ==========================================
-- This table mirrors auth.users to allow public access to user info (name, avatar)
create table if not exists public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  email text,
  full_name text,
  avatar_url text,
  role text default 'user', -- 'user' or 'admin'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Trigger to handle new user signup automatically
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Trigger execution
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ==========================================
-- 2. SONGS (Local Library)
-- ==========================================
create table if not exists public.songs (
  id bigint primary key generated always as identity,
  title text not null,
  artist text not null,
  album text,
  category text, 
  song_url text not null,
  image_url text, 
  duration integer, -- in seconds
  plays bigint default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- 3. PODCASTS & EPISODES
-- ==========================================
create table if not exists public.podcasts (
  id uuid default uuid_generate_v4() primary key,
  title text not null,
  publisher text,
  description text,
  image_url text,
  category text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.episodes (
  id uuid default uuid_generate_v4() primary key,
  podcast_id uuid references public.podcasts(id) on delete cascade not null,
  title text not null,
  description text,
  duration text, 
  audio_url text not null,
  plays bigint default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- 4. PLAYLISTS system
-- ==========================================
create table if not exists public.playlists (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users(id) on delete cascade not null, 
  name text not null,
  description text,
  is_public boolean default false,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.playlist_tracks (
  id uuid default uuid_generate_v4() primary key,
  playlist_id uuid references public.playlists(id) on delete cascade not null,
  track_id text not null, -- Can be local ID (stringified) or Spotify ID
  source text default 'local', -- 'local', 'spotify', 'audius'
  external_data jsonb, -- Metadata snapshot { title, artist, image }
  added_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(playlist_id, track_id) 
);

-- ==========================================
-- 5. USER INTERACTIONS (Likes & History)
-- ==========================================
create table if not exists public.favorites (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  song_id text not null,
  source text default 'local', -- 'local', 'spotify'
  external_data jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, song_id)
);

create table if not exists public.recently_played (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  track_id text, -- Unified ID
  source text default 'local',
  external_data jsonb,
  played_at timestamp with time zone default now()
);

-- ==========================================
-- 6. ROW LEVEL SECURITY (RLS)
-- ==========================================
-- Allow public read access to content
alter table songs enable row level security;
create policy "Public view songs" on songs for select using (true);
create policy "Admin manage songs" on songs for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

alter table podcasts enable row level security;
create policy "Public view podcasts" on podcasts for select using (true);
create policy "Admin manage podcasts" on podcasts for all using (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

alter table episodes enable row level security;
create policy "Public view episodes" on episodes for select using (true);

-- User Private Data
alter table playlists enable row level security;
create policy "View own playlists" on playlists for select using (auth.uid() = user_id or is_public = true);
create policy "Manage own playlists" on playlists for all using (auth.uid() = user_id);

alter table playlist_tracks enable row level security;
create policy "View playlist tracks" on playlist_tracks for select using (
  exists (select 1 from playlists p where p.id = playlist_tracks.playlist_id and (p.user_id = auth.uid() or p.is_public = true))
);
create policy "Modify playlist tracks" on playlist_tracks for all using (
  exists (select 1 from playlists p where p.id = playlist_tracks.playlist_id and p.user_id = auth.uid())
);

alter table favorites enable row level security;
create policy "Manage own favorites" on favorites for all using (auth.uid() = user_id);

alter table recently_played enable row level security;
create policy "Manage own history" on recently_played for all using (auth.uid() = user_id);

alter table profiles enable row level security;
create policy "Public view profiles" on profiles for select using (true);
create policy "User update own profile" on profiles for update using (auth.uid() = id);

-- ==========================================
-- 7. SEED DATA (Major/Minor Data)
-- ==========================================

-- Insert sample categories if you had a categories table (we use text columns, so no need)

-- Example: Insert a test admin user (Ensure you replace with real UUID after signup)
-- update public.profiles set role = 'admin' where email = 'admin@streamlite.com';

-- Example: Sample Song (For reference)
-- insert into songs (title, artist, album, category, song_url, image_url, duration)
-- values ('StreamLite Theme', 'System', 'OST', 'Electronic', 'https://example.com/song.mp3', 'https://example.com/cover.jpg', 120);
